### PR TITLE
updated data.json

### PR DESCRIPTION
**Pull request by Jassi10000**
Successfully sent the PR

### CODE REVIEW

**Review by w3bdesign — APPROVED** [review]

**Comment by dumbcoder7** [comment]
The GitHub Action broke again. I think the Action is coded wrongly?

**Comment by Jassi10000** [comment]
I also think same @dumbcoder7 , maybe @eddiejaoude  can have a look over it when he's free

**Comment by AllanRegush** [comment]
the action has problems branches with `-`

**Review by AllanRegush — APPROVED** [review]
Looks Good :+1: Thank you

**Comment by Jassi10000** [comment]
> Looks Good 👍 Thank you

Thank you sir for merging my changes irrespective of the problems occured

**Pull request merged**
