### PR TITLE
Added my profile

### PR DESCRIPTION
**Pull request by makuzaverite**

### CODE REVIEW

**Comment by AllanRegush** [comment]
Thank You for you PR it appears the Prettier action has failed. 

If you need any help let us know 🤓 

Please add only to the bottom of the file. It makes it easier to see what has changed. 😄

**Comment by makuzaverite** [comment]
I think the problem is your own checks not my problem

**Comment by Vyvy-vi** [comment]
I think the checks are failing since they can't find the forked repository.
Screenshot 2020-12-17 at 11 15 42 PM

**Comment by AllanRegush** [comment]
@Vyvy-vi your probably right.

**Comment by AllanRegush** [comment]
From the log:
> Error: A branch or tag with the name 'patch-1' could not be found

**Review by AllanRegush — APPROVED** [review]
Thank you 👍

**Pull request merged**
