### PR TITLE
Update data.json file

### PR DESCRIPTION
**Pull request by TawfikYasser**
Added my json object for my profile image.

### CODE REVIEW

**Comment by TawfikYasser** [comment]
I have a problem please help me @eddiejaoude

**Comment by AllanRegush** [comment]
@TawfikYasser The prettier check action has trouble with branches with `-` in them.

**Review by AllanRegush — APPROVED** [review]
Thank You 👍 Looks Good 😄

**Comment by TawfikYasser** [comment]
Oh yes, I got that, Thank you very much @AllanRegush .

**Pull request merged**
