### PR TITLE
Add Michelle Sandford

### PR DESCRIPTION
**Pull request by msandfor**
Issue #125

Hope I've done it correctly with 3 images. Let me know if I need to change anything.

M

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you @msandfor , your GitHub profile is epic 👍 - unfortunately at the moment we only support 1 image

**Comment by msandfor** [comment]
You are very kind @eddiejaoude I should probably just use the first one then? Or should I try and zoom out to get a tiny image across the whole thing? Do I edit the file and make a new PR - I actually haven't done an edit from this side of the PR before....

**Comment by eddiejaoude** [comment]
I think we can make improvements to the Action in the future to handle multiple images. For now, probably using the first image is best - I think there is a tool that will stitch the images together to make 1 longer image but I am not sure what it is.

To update your PR, you can push another commit to your branch in your fork (or hit the edit button in the changes in this PR)

**Comment by msandfor** [comment]
OK, I think I have done that :-)

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
Thanks @msandfor 👍

**Pull request merged**
