### PR TITLE
Added my profile to data.json

### PR DESCRIPTION
**Pull request by ritik307**

### CODE REVIEW

**Review by AllanRegush — APPROVED** [review]
Looks Good 👍 Thank You

**Comment by AllanRegush** [comment]
Looks like there is a conflict. Could you please resolve it? Thanks. 😄

**Comment by ritik307** [comment]
> 
> 
> Looks Good 👍 Thank You

Thank you

**Comment by ritik307** [comment]
> 
> 
> Looks like there is a conflict. Could you please resolve it? Thanks. 😄

Can you please tell me how can i fix the conflict?

**Comment by ritik307** [comment]
@AllanRegush  I have tried to fix the conflict can you please look into that

**Review by ritik307 — COMMENTED** [review]
removed extra space in between `}  ,`

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
