### PR TITLE
Add prettier to project

### PR DESCRIPTION
**Pull request by stemount**
references #173 - @alrifay noticed there is an issue upstream that may take some time to fix.

### CODE REVIEW

**Comment by stemount** [comment]
Time to break this!!!!!!!!!!

**Comment by eddiejaoude** [comment]
Yay awesome 👍

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍

**Comment by stemount** [comment]
Closes #173

**Comment by stemount** [comment]
open source ftw, mistake PRd into upstream https://github.com/EddieJaoudeCommunity/awesome-github-profiles/pull/175

**Pull request merged**
