### PR TITLE
Updated data.json

### PR DESCRIPTION
**Pull request by saumya66**

### CODE REVIEW

**Comment by eddiejaoude** [comment]
This looks good, did you mean to close this?

**Comment by saumya66** [comment]
> This looks good, did you mean to close this?

Ya ya, it was not passing the Prettier check for some reason.

**Comment by eddiejaoude** [comment]
Ok. Btw for future reference you can update PRs, but pushing commits to the same branch and GitHub will update the PR

**Comment by saumya66** [comment]
> Ok. Btw for future reference you can update PRs, but pushing commits to the same branch and GitHub will update the PR

Ohh, okay learnt that now. Thanks !

**Comment by eddiejaoude** [comment]
no problem 🤓

**Pull request closed without merging**
