### PR TITLE
Added my profile to the list.

### LINKED ISSUE #217: Utkarsh Singh
GitHubprof

### PR DESCRIPTION
**Pull request by Utkarsh299-tech**
Closes #217

### CODE REVIEW

**Review by AllanRegush — APPROVED** [review]
Looks Good 👍

**Comment by AllanRegush** [comment]
There is a merge conflict. Could you resolve this? Thanks 😄

**Comment by Utkarsh299-tech** [comment]
> Looks Good 👍

Thank you!

**Comment by Utkarsh299-tech** [comment]
> There is a merge conflict. Could you resolve this? Thanks 😄

Can you please tell me how should I resolve this conflict?

**Comment by Utkarsh299-tech** [comment]
> > There is a merge conflict. Could you resolve this? Thanks 😄
> 
> Can you please tell me how should I resolve this conflict?

I tried resolving that conflict. Please see to it. Thanks 😃

**Comment by eddiejaoude** [comment]
Thank you all 👍 - looks good

**Comment by Utkarsh299-tech** [comment]
> Thank you all 👍 - looks good

Thank you all! 😀

**Pull request merged**
