### PR TITLE
#173 add prettier github workflow action to project

### PR DESCRIPTION
**Pull request by stemount**

### CODE REVIEW

**Comment by alrifay** [comment]
The action didn't work because the branch name contains `/`, see https://github.com/EddieJaoudeCommunity/gh-actions-html-table-generator/issues/17 for more details

**Comment by stemount** [comment]
good spot @alrifay hmm, damn, will look at that issue first.

**Comment by eddiejaoude** [comment]
@alrifay stops everything ❤️ .

Oh no sorry to give you more work @stemount 🤓

**Comment by eddiejaoude** [comment]
**spots** not *stops* - stupid auto correct 🤦‍♂️ - I updated it now 😂

**Pull request closed without merging**
